# Generated by Django 2.1.3 on 2019-07-19 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='trans_date_time',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
