# Generated by Django 2.1.3 on 2019-07-19 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0002_message_trans_date_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='trans_date_time',
            new_name='message_date_time',
        ),
    ]
