# Generated by Django 2.1.3 on 2019-07-21 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0003_auto_20190719_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='has_reply_from_recipients',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='trashed_by_creator',
            field=models.BooleanField(default=False),
        ),
    ]
