# Generated by Django 2.1.3 on 2019-07-21 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0004_auto_20190721_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='deleted_from_mail_box',
            field=models.BooleanField(default=False),
        ),
    ]
