# Generated by Django 2.1.3 on 2019-07-22 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0005_messagerecipient_deleted_from_mail_box'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='has_reply_from_recipients',
        ),
    ]
