# Generated by Django 2.1.3 on 2019-07-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0006_remove_message_has_reply_from_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_from_mail_box',
            field=models.BooleanField(default=False),
        ),
    ]
