# Generated by Django 2.1.3 on 2019-07-28 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0007_message_deleted_from_mail_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecipient',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_recipients', to='MasterDataManagement.Message'),
        ),
    ]
