# Generated by Django 2.1.3 on 2019-07-31 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0008_auto_20190728_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
