# Generated by Django 2.1.3 on 2019-08-02 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0009_auto_20190731_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcommoditybalance',
            name='status',
            field=models.CharField(default='active', max_length=100),
        ),
        migrations.AlterField(
            model_name='healthcommoditybalance',
            name='health_commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterDataManagement.HealthCommodity'),
        ),
        migrations.AlterField(
            model_name='healthcommoditybalance',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterDataManagement.Location'),
        ),
        migrations.AlterField(
            model_name='healthcommoditytransactions',
            name='posting_schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterDataManagement.PostingSchedule'),
        ),
    ]
