# Generated by Django 2.1.3 on 2019-08-04 22:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0010_auto_20190802_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcommoditybalance',
            name='health_commodity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='MasterDataManagement.HealthCommodity'),
        ),
        migrations.AlterField(
            model_name='healthcommoditytransactions',
            name='posting_schedule',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='MasterDataManagement.PostingSchedule'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='healthcommoditytransactions',
            name='user_created',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterDataManagement.Location'),
        ),
    ]
