# Generated by Django 2.1.3 on 2019-08-12 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0013_healthcommodity_elmis_product_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='common_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
