# Generated by Django 2.1.3 on 2019-09-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0014_location_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcommodity',
            name='elmis_product_code',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='location',
            name='elims_facility_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
