# Generated by Django 2.1.3 on 2019-09-13 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0015_auto_20190908_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcommoditybalance',
            name='quantity_available',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthcommoditybalance',
            name='quantity_consumed',
            field=models.IntegerField(default=0),
        ),
    ]
