# Generated by Django 2.1.3 on 2019-09-13 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0016_auto_20190913_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='healthcommoditybalance',
            name='quantity_available',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthcommoditybalance',
            name='quantity_consumed',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
