# Generated by Django 2.1.3 on 2019-09-23 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0017_auto_20190913_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcommoditytransactions',
            name='periodic_consumption',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
