# Generated by Django 2.1.3 on 2019-09-23 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0018_healthcommoditytransactions_periodic_consumption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcommoditytransactions',
            name='periodic_consumption',
        ),
    ]
