# Generated by Django 2.1.3 on 2019-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0019_remove_healthcommoditytransactions_periodic_consumption'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcommoditybalance',
            name='has_patients',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcommoditybalance',
            name='number_of_clients',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcommoditybalance',
            name='stock_out_days',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
