# Generated by Django 2.1.3 on 2019-09-23 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0020_auto_20190923_1408'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcommoditybalance',
            old_name='has_patients',
            new_name='has_clients',
        ),
    ]
