# Generated by Django 2.1.3 on 2019-09-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0021_auto_20190923_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthcommoditybalance',
            name='quantity_expired',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='healthcommoditybalance',
            name='quantity_wasted',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
