# Generated by Django 2.1.3 on 2019-10-22 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0022_auto_20190926_1700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='healthcommodity',
            old_name='elmis_product_code',
            new_name='elmis_product_id',
        ),
        migrations.AlterField(
            model_name='location',
            name='elims_facility_id',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
