# Generated by Django 2.1.3 on 2019-10-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0024_auto_20191022_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='elims_facility_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
