# Generated by Django 2.1.3 on 2019-07-17 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firebasetokenmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='FireBaseTokenModel',
        ),
    ]
