# Generated by Django 2.1.3 on 2019-07-17 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0002_auto_20190717_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='reg_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
