# Generated by Django 2.1.3 on 2019-07-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0003_auto_20190717_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dev_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
