# Generated by Django 2.1.3 on 2019-09-08 20:59

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0007_auto_20190908_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='UserManagement.Profile'),
        ),
    ]
