# Generated by Django 2.1.3 on 2019-09-08 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0008_profile_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='parent',
        ),
    ]
