# Generated by Django 2.1.3 on 2019-09-19 06:54

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('UserManagement', '0009_remove_profile_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=mptt.fields.TreeForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MasterDataManagement.Location'),
        ),
    ]
