# Generated by Django 2.1.3 on 2019-09-19 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterDataManagement', '0017_auto_20190913_1107'),
        ('UserManagement', '0010_auto_20190919_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilitySettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('elims_reporting_period_in_days', models.IntegerField()),
                ('facility_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MasterDataManagement.Location')),
            ],
            options={
                'db_table': 'HCT_FacilitySettings',
            },
        ),
    ]
